### ISSUE TITLE
install.py not working for Raspberry Pi OS Lite 64 bit

### ISSUE THREAD

**Issue by ikbenmacje** [abstractfoundry/lumicube-daemon#1]
When running the command:

`python3 <(curl -fL https://www.abstractfoundry.com/lumicube/download/install.py)
`

as documented here: https://abstractfoundry.com/lumicube/resources/

The script returns:

```
 File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'curl -fL https://www.abstractfoundry.com/lumicube/download/Daemon-1.4-x64.AppImage > /home/pi/AbstractFoundry/Daemon/Software/Daemon-1.4-x64.AppImage' returned non-zero exit status 22.
```
This is because with the 64 bit version of Raspberry Pi the Python command `platform.machine()` returns `'aarch64'` and thus the installer script tries to download "https://www.abstractfoundry.com/lumicube/download/Daemon-1.4-x64.AppImage" which does not exist at the time of writing this issue. However the file "https://www.abstractfoundry.com/lumicube/download/Daemon-1.4-arm.AppImage" does exist.

**Comment by aaronlower** [comment]
+1 - hitting the same. Should https://www.abstractfoundry.com/lumicube/download/latest_daemon.txt actually be 1.3?

**Comment by ikbenmacje** [comment]
Having been in contact with abstractfoundry they confirm that at the moment their installation script and tools are written for the 32 bit version of Rapsberry PI OS. So if you run into this issue please use the 32bit version of the Rapsberry PI OS.
