### ISSUE TITLE
Testing feedback loop

### ISSUE THREAD

**Issue by mfoo** [abstractfoundry/lumicube-daemon#11]
I have been thinking about seeing if I can contribute any changes (initially perhaps just documentation), but I've been a little confused on the feedback loop.

How are you currently testing the changes that you make? Does the process essentially look like this:
- Modify code
- Build with Maven
- Unzip on Pi
- Restart service on Pi

This would be good information to have in a `CONTRIBUTING.md` or similar.

**Comment by mfoo** [comment]
Will try connecting directly to the board with a USB TTL serial adapter later - that should bypass the Pi and shorten the loop!

**Comment by mfoo** [comment]
I've been testing the USB TTL serial adapter so that I can connect directly from my laptop and bypass the Pi, but I'm having some trouble and I wondered if you had encountered this before or if you had any tips.

I've added a little logging and I can see the Java code picks up the correct port and adapter:

```
18:11:19.852 [main] INFO  c.a.daemon.serial.SerialDriver - Using serial port CP2104 USB to UART Bridge Controller at ttyUSB0
```

and for some reason the chip tunes module works apparently regardless of which way round I connect the tx/rx pins.

But whenever I test a module requiring the screen I'm getting the following:

```
17:19:28.128 [Foundry Client Domain Socket] ERROR c.a.d.s.SocketChannelClientHandler - Error processing command.
java.lang.IllegalStateException: Destination unavailable.
	at com.abstractfoundry.daemon.server.method.node.display.DisplaySetMethod.invoke(DisplaySetMethod.java:81)
	at com.abstractfoundry.daemon.server.GenericSocketClientHandler.handle(GenericSocketClientHandler.java:98)
	at com.abstractfoundry.daemon.server.SocketChannelClientHandler.loop(SocketChannelClientHandler.java:120)
	at com.abstractfoundry.daemon.server.SocketChannelClientHandler.spin(SocketChannelClientHandler.java:137)
	at com.abstractfoundry.daemon.server.SocketChannelClientHandler.run(SocketChannelClientHandler.java:149)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

also the UI shows "no modules connected". The offending line is this one, and I'm struggling to see where this gets populated:

```java
store.getNamespace().getModule("display");
```

I've tested the same serial adapter on both my laptop and on the Pi itself and both result in the same issue, but switching to the Pi and the provided cable works fine:

```
There are 4 modules connected: display, microphone, screen, speaker
```

I've also tested with a Bus Pirate v3.6 (2012):
```
18:33:25.954 [main] INFO  c.a.daemon.serial.SerialDriver - Using serial port FT232R USB UART at ttyUSB0
```

and this won't even start chip tunes. I know I'm doing something wrong but I don't know what it is and any help would be appreciated!

**Comment by abstractfoundry** [comment]
Hi @mfoo my guess is that the chip tunes only appear to work when you run it on your laptop, as it's probably using your laptop speakers, and the connection to the cube isn't working at all. I've not tried using a CP2104 bridge, but it might be struggling with the 3 Mbps baudrate (although I would have thought it would work OK). There's a hidden feature of the cube which will probably help you: if you connect your laptop to the cube's Micro-B port, there's a virtual serial port there which we use regularly to reduce our testing feedback loop. But please BE WARNED: if you don't also power the cube via the USB-C port at the same time, it will draw power from your laptop (potentially 3A or more!) so please use this debug port carefully. If you want to be extra careful, you could modify a spare Micro-B cable, cutting just the 5V wire somewhere along its length.

**Comment by mfoo** [comment]
Ah interesting, thanks for the tip.

I've had a look at my three devices that can perform USB serial connections. My experience level isn't high here but the internet suggests that the CP2104 might not support 3 megabaud but my Bus Pirate (which uses FT232R) should be fine.

As an added complexity, I only have USB-C ports, so I'm using an adapter. To rule that out I connected the Bus Pirate to the Pi's USB-3 port and I'm experiencing the same issues.

I then found a USB Micro-B cable to my Pi and tested the virtual serial port, but somehow just before testing, the (new) SD card on my Pi failed! I'm using Sandisk Extreme Pro Class 10 V30 micro SDXC cards ([this one](https://www.amazon.co.uk/SanDisk-Extreme-microSDXC-Adapter-Performance/dp/B07G3GMRYF?th=1)) and this is now the fourth one that's failed. Oddly I've also had two Pis using them for 400+ days running Kubernetes without issues. Essentially they always fail in the same way - they become read only and they acknowledge writes, but when you read the data back it is as if it wasn't ever written.

```
[  750.443232] blk_update_request: I/O error, dev mmcblk0, sector 3709232 op 0x1:(WRITE) flags 0x800 phys_seg 6 prio class 0
[  750.443358] Aborting journal on device mmcblk0p2-8.
[  750.443491] EXT4-fs error (device mmcblk0p2): ext4_journal_check_start:83: comm systemd-journal: Detected aborted journal
[  750.445516] EXT4-fs error (device mmcblk0p2): ext4_journal_check_start:83: comm rs:main Q:Reg: Detected aborted journal
[  750.445545] blk_update_request: I/O error, dev mmcblk0, sector 3672064 op 0x1:(WRITE) flags 0x800 phys_seg 1 prio class 0
[  750.445580] blk_update_request: I/O error, dev mmcblk0, sector 3672064 op 0x1:(WRITE) flags 0x800 phys_seg 1 prio class 0
[  750.445601] Buffer I/O error on dev mmcblk0p2, logical block 393216, lost sync page write
[  750.445639] JBD2: Error -5 detected when updating journal superblock for mmcblk0p2-8.
[  750.447856] blk_update_request: I/O error, dev mmcblk0, sector 526336 op 0x1:(WRITE) flags 0x3800 phys_seg 1 prio class 0
[  750.447890] blk_update_request: I/O error, dev mmcblk0, sector 526336 op 0x1:(WRITE) flags 0x3800 phys_seg 1 prio class 0
[  750.447911] Buffer I/O error on dev mmcblk0p2, logical block 0, lost sync page write
[  750.447952] EXT4-fs (mmcblk0p2): I/O error while writing superblock
[  750.447958] EXT4-fs (mmcblk0p2): I/O error while writing superblock
[  750.447976] EXT4-fs (mmcblk0p2): Remounting filesystem read-only
[  750.447996] EXT4-fs (mmcblk0p2): Remounting filesystem read-only
```

When booting now I get an initramfs prompt :disappointed:.

(for anybody reading this who's interested in card failure, they try and protect themselves by preventing writes after certain scenarios and there's nothing to do except get a new card)

From `dmesg`, it looks like this happened shortly _before_ I connected the Micro SD cable, and the board was powered separately, so I don't think they're related, but now I need to find time to flash Ubuntu again onto a new card - I'd like to confirm it's working over Micro USB without a USB-C adapter and on the relatively cheap Pi before testing on my laptop!

Will report back when I have some more information!

EDIT:

> my guess is that the chip tunes only appear to work when you run it on your laptop, as it's probably using your laptop speakers

This was correct!

**Comment by mfoo** [comment]
Can confirm on a newly flashed Pi (Ubuntu 22.04.1 LTS 64 bit) using the micro USB connection it's working as expected. Thanks!

**Comment by abstractfoundry** [comment]
Awesome, glad to hear that's working for you @mfoo.
