### ISSUE TITLE
Uploaded Scripts

### ISSUE THREAD

**Issue by sgutermann** [abstractfoundry/lumicube-daemon#14]
The interface allows for scripts to be uploaded. The do get uploaded and simply dropped on the users Desktop.

After that they are not accessible in the interface or anywhere (except the Desktop of course).

1. I do not think that the "Desktop" is a safe space to drop those scripts.
2. I would like to use them on the lumicube, ideally in a drop down similar to "Projects"
3. Would wish for actively editing and saving them gain ... but that is a wish for now.

**Comment by abstractfoundry** [comment]
Hi @sgutermann thanks for the suggestion - we are working on improving this part of the UI soon.

**Comment by abstractfoundry** [comment]
This has now been implemented, and released in version 1.8.
