### ISSUE TITLE
Maven versioning

### ISSUE THREAD

**Issue by mfoo** [abstractfoundry/lumicube-daemon#2]
Hello!

I just got back from holiday to find my Lumicube had been delivered :smile:.

I currently have a small Kubernetes (k3s) cluster of two Pi 4Bs and I have a third Pi 4B sitting around doing nothing. I plan on adding it to my cluster and running Lumicube on the third Pi and I expect I'll have to make some changes, and possibly add documentation if this is something other people would want.

Other things we could be improved would be to e.g. enable GitHub pipelines to parse the JUnit output in case some changes introduce issues and to configure Dependabot to keep versions up-to-date.

In order to facilitate making changes, would it be possible to have the `main` branch represent the current development state, and to move to tags in git for releases? I.e.,

```
git checkout main
git tag releases/1.3
mvn versions:set -DnewVersion=1.4-SNAPSHOT
git commit -am "Bump to 1.4-SNAPSHOT"
git push --tags
```

(or something like this)

That would mean that we can raise MRs and they can be merged without bumping the release version and then releases can be made as necessary and tagged, so `main` always contains a snapshot version.

**Comment by abstractfoundry** [comment]
Very sensible @mfoo, have just done as you suggested, and I'll follow this scheme in the future (actually I should have done it before merging some commits really, but hopefully the main branch is now in good shape going forward). Cheers.
