### ISSUE TITLE
Error update 1.8

### ISSUE THREAD

**Issue by nsk** [abstractfoundry/lumicube-daemon#21]
landing page : Upgrading to version 1.8, after the download completes the system will restart.

http://192.168.178.36/api/v1/tools/upgrade

No reboot , no DL

**Comment by nsk** [comment]
after install 1.8 update , the lumicube does not boot anymore, even after several reboots and shutdowns, but I still have access to the raspberry PI in ssh, a way to see the logs to know what is going on??

**Comment by nsk** [comment]
After restarting the installation script, the cube works again 👍 


pi@Chester:~ $ python3 <(curl -fL https://www.abstractfoundry.com/lumicube/download/install.py)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8062  100  8062    0     0  14168      0 --:--:-- --:--:-- --:--:-- 14193
Installing system dependencies...
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian bullseye InRelease [23.6 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.2 MB]
Get:4 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [301 kB]
Fetched 13.6 MB in 11s (1,236 kB/s)                                                                        
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
5 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.74.0-1.3+deb11u3).
iptables is already the newest version (1.8.7-1).
libfuse2 is already the newest version (2.9.9-5).
python3 is already the newest version (3.9.2-3).
unzip is already the newest version (6.0-26+deb11u1).
python3-pip is already the newest version (20.3.4-4+rpt1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in ./.local/lib/python3.9/site-packages (22.2.2)
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: flask==2.1.2 in ./.local/lib/python3.9/site-packages (2.1.2)
Requirement already satisfied: waitress==2.1.1 in ./.local/lib/python3.9/site-packages (2.1.1)
Requirement already satisfied: itsdangerous>=2.0 in ./.local/lib/python3.9/site-packages (from flask==2.1.2) (2.1.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in ./.local/lib/python3.9/site-packages (from flask==2.1.2) (5.0.0)
Requirement already satisfied: Werkzeug>=2.0 in ./.local/lib/python3.9/site-packages (from flask==2.1.2) (2.2.2)
Requirement already satisfied: Jinja2>=3.0 in ./.local/lib/python3.9/site-packages (from flask==2.1.2) (3.1.2)
Requirement already satisfied: click>=8.0 in ./.local/lib/python3.9/site-packages (from flask==2.1.2) (8.1.3)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->flask==2.1.2) (3.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./.local/lib/python3.9/site-packages (from Jinja2>=3.0->flask==2.1.2) (2.1.1)
Configuring the serial interface...
Installing the Abstract Foundry Daemon...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  204M  100  204M    0     0  3391k      0  0:01:01  0:01:01 --:--:-- 2932k
Created symlink /home/pi/.config/systemd/user/default.target.wants/foundry-daemon.service → /home/pi/.local/share/systemd/user/foundry-daemon.service.
Configuring iptables rules...
Created symlink /etc/systemd/system/multi-user.target.wants/foundry-redirect.service → /etc/systemd/system/foundry-redirect.service.
Installing addon packages...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
espeak is already the newest version (1.48.15+dfsg-2).
python3-cffi is already the newest version (1.14.5-1).
python3-matplotlib is already the newest version (3.3.4-1).
python3-numpy is already the newest version (1:1.19.5-1).
python3-requests is already the newest version (2.25.1+dfsg-2).
ffmpeg is already the newest version (7:4.3.4-0+deb11u1+rpt3).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyalsaaudio==0.9.0 in ./.local/lib/python3.9/site-packages (0.9.0)
Requirement already satisfied: pyttsx3==2.90 in ./.local/lib/python3.9/site-packages (2.90)
Requirement already satisfied: precise-runner==0.3.1 in ./.local/lib/python3.9/site-packages (0.3.1)
Requirement already satisfied: vosk==0.3.32 in ./.local/lib/python3.9/site-packages (0.3.32)
Requirement already satisfied: pyaudio in ./.local/lib/python3.9/site-packages (from precise-runner==0.3.1) (0.2.12)
Requirement already satisfied: cffi>=1.0 in /usr/lib/python3/dist-packages (from vosk==0.3.32) (1.14.5)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39.2M  100 39.2M    0     0  2704k      0  0:00:14  0:00:14 --:--:-- 3009k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 62.4M  100 62.4M    0     0  2338k      0  0:00:27  0:00:27 --:--:-- 1595k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 26556  100 26556    0     0  40605      0 --:--:-- --:--:-- --:--:-- 3131k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   132  100   132    0     0    113      0  0:00:01  0:00:01 --:--:--     0
Archive:  /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15.zip
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/am/final.mdl  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/graph/disambig_tid.int  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/graph/HCLr.fst  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/graph/Gr.fst  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/graph/phones/word_boundary.int  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/conf/model.conf  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/conf/mfcc.conf  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/ivector/splice.conf  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/ivector/final.dubm  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/ivector/global_cmvn.stats  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/ivector/final.ie  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/ivector/online_cmvn.conf  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/ivector/final.mat  
  inflating: /home/pi/AbstractFoundry/Daemon/Voice/vosk-model-small-en-us-0.15/README  
precise-engine/
precise-engine/libcrypto.so.1.0.0
precise-engine/mmap.cpython-34m-arm-linux-gnueabihf.so
precise-engine/audioop.cpython-34m-arm-linux-gnueabihf.so
precise-engine/libstdc++.so.6
precise-engine/termios.cpython-34m-arm-linux-gnueabihf.so
precise-engine/_codecs_iso2022.cpython-34m-arm-linux-gnueabihf.so
precise-engine/resource.cpython-34m-arm-linux-gnueabihf.so
precise-engine/libmpdec.so.2
precise-engine/lib/
precise-engine/lib/python3.4/
precise-engine/lib/python3.4/config-3.4m-arm-linux-gnueabihf/
precise-engine/lib/python3.4/config-3.4m-arm-linux-gnueabihf/Makefile
precise-engine/numpy/
precise-engine/numpy/linalg/
precise-engine/numpy/linalg/_umath_linalg.cpython-34m.so
precise-engine/numpy/linalg/lapack_lite.cpython-34m.so
precise-engine/numpy/random/
precise-engine/numpy/random/mtrand.cpython-34m.so
precise-engine/numpy/fft/
precise-engine/numpy/fft/fftpack_lite.cpython-34m.so
precise-engine/numpy/core/
precise-engine/numpy/core/_multiarray_tests.cpython-34m.so
precise-engine/numpy/core/umath.cpython-34m.so
precise-engine/numpy/core/multiarray.cpython-34m.so
precise-engine/libhdf5_serial.so.8
precise-engine/libatlas.so.3
precise-engine/libssl.so.1.0.0
precise-engine/liblzma.so.5
precise-engine/scipy/
precise-engine/scipy/spatial/
precise-engine/scipy/spatial/_voronoi.cpython-34m.so
precise-engine/scipy/spatial/qhull.cpython-34m.so
precise-engine/scipy/spatial/_distance_wrap.cpython-34m.so
precise-engine/scipy/spatial/_hausdorff.cpython-34m.so
precise-engine/scipy/spatial/ckdtree.cpython-34m.so
precise-engine/scipy/_lib/
precise-engine/scipy/_lib/_ccallback_c.cpython-34m.so
precise-engine/scipy/_lib/messagestream.cpython-34m.so
precise-engine/scipy/_lib/_fpumode.cpython-34m.so
precise-engine/scipy/linalg/
precise-engine/scipy/linalg/_flinalg.cpython-34m.so
precise-engine/scipy/linalg/_clapack.cpython-34m.so
precise-engine/scipy/linalg/_fblas.cpython-34m.so
precise-engine/scipy/linalg/_flapack.cpython-34m.so
precise-engine/scipy/linalg/_decomp_update.cpython-34m.so
precise-engine/scipy/linalg/_cblas.cpython-34m.so
precise-engine/scipy/linalg/cython_blas.cpython-34m.so
precise-engine/scipy/linalg/cython_lapack.cpython-34m.so
precise-engine/scipy/linalg/_solve_toeplitz.cpython-34m.so
precise-engine/scipy/sparse/
precise-engine/scipy/sparse/_sparsetools.cpython-34m.so
precise-engine/scipy/sparse/linalg/
precise-engine/scipy/sparse/linalg/dsolve/
precise-engine/scipy/sparse/linalg/dsolve/_superlu.cpython-34m.so
precise-engine/scipy/sparse/linalg/eigen/
precise-engine/scipy/sparse/linalg/eigen/arpack/
precise-engine/scipy/sparse/linalg/eigen/arpack/_arpack.cpython-34m.so
precise-engine/scipy/sparse/linalg/isolve/
precise-engine/scipy/sparse/linalg/isolve/_iterative.cpython-34m.so
precise-engine/scipy/sparse/csgraph/
precise-engine/scipy/sparse/csgraph/_min_spanning_tree.cpython-34m.so
precise-engine/scipy/sparse/csgraph/_reordering.cpython-34m.so
precise-engine/scipy/sparse/csgraph/_tools.cpython-34m.so
precise-engine/scipy/sparse/csgraph/_shortest_path.cpython-34m.so
precise-engine/scipy/sparse/csgraph/_traversal.cpython-34m.so
precise-engine/scipy/sparse/_csparsetools.cpython-34m.so
precise-engine/scipy/optimize/
precise-engine/scipy/optimize/_nnls.cpython-34m.so
precise-engine/scipy/optimize/_lsq/
precise-engine/scipy/optimize/_lsq/givens_elimination.cpython-34m.so
precise-engine/scipy/optimize/_lbfgsb.cpython-34m.so
precise-engine/scipy/optimize/_slsqp.cpython-34m.so
precise-engine/scipy/optimize/minpack2.cpython-34m.so
precise-engine/scipy/optimize/_group_columns.cpython-34m.so
precise-engine/scipy/optimize/_cobyla.cpython-34m.so
precise-engine/scipy/optimize/_zeros.cpython-34m.so
precise-engine/scipy/optimize/_minpack.cpython-34m.so
precise-engine/scipy/optimize/moduleTNC.cpython-34m.so
precise-engine/scipy/optimize/_trlib/
precise-engine/scipy/optimize/_trlib/_trlib.cpython-34m.so
precise-engine/scipy/interpolate/
precise-engine/scipy/interpolate/_ppoly.cpython-34m.so
precise-engine/scipy/interpolate/_fitpack.cpython-34m.so
precise-engine/scipy/interpolate/dfitpack.cpython-34m.so
precise-engine/scipy/interpolate/_bspl.cpython-34m.so
precise-engine/scipy/interpolate/interpnd.cpython-34m.so
precise-engine/scipy/integrate/
precise-engine/scipy/integrate/lsoda.cpython-34m.so
precise-engine/scipy/integrate/_odepack.cpython-34m.so
precise-engine/scipy/integrate/_dop.cpython-34m.so
precise-engine/scipy/integrate/_quadpack.cpython-34m.so
precise-engine/scipy/integrate/vode.cpython-34m.so
precise-engine/scipy/ndimage/
precise-engine/scipy/ndimage/_nd_image.cpython-34m.so
precise-engine/scipy/ndimage/_ni_label.cpython-34m.so
precise-engine/scipy/fftpack/
precise-engine/scipy/fftpack/convolve.cpython-34m.so
precise-engine/scipy/fftpack/_fftpack.cpython-34m.so
precise-engine/scipy/stats/
precise-engine/scipy/stats/statlib.cpython-34m.so
precise-engine/scipy/stats/_stats.cpython-34m.so
precise-engine/scipy/stats/mvn.cpython-34m.so
precise-engine/scipy/special/
precise-engine/scipy/special/_ufuncs.cpython-34m.so
precise-engine/scipy/special/_ellip_harm_2.cpython-34m.so
precise-engine/scipy/special/_comb.cpython-34m.so
precise-engine/scipy/special/specfun.cpython-34m.so
precise-engine/scipy/special/_ufuncs_cxx.cpython-34m.so
precise-engine/_ssl.cpython-34m-arm-linux-gnueabihf.so
precise-engine/libopenblas.so.0
precise-engine/_json.cpython-34m-arm-linux-gnueabihf.so
precise-engine/libgcc_s.so.1
precise-engine/_lzma.cpython-34m-arm-linux-gnueabihf.so
precise-engine/liblapack.so.3
precise-engine/_decimal.cpython-34m-arm-linux-gnueabihf.so
precise-engine/tensorflow/
precise-engine/tensorflow/python/
precise-engine/tensorflow/python/_pywrap_tensorflow_internal.so
precise-engine/tensorflow/python/framework/
precise-engine/tensorflow/python/framework/fast_tensor_util.so
precise-engine/libffi.so.6
precise-engine/libhdf5_serial_hl.so.8
precise-engine/_codecs_kr.cpython-34m-arm-linux-gnueabihf.so
precise-engine/libgfortran.so.3
precise-engine/_sqlite3.cpython-34m-arm-linux-gnueabihf.so
precise-engine/lib2to3/
precise-engine/lib2to3/Grammar.txt
precise-engine/lib2to3/PatternGrammar.txt
precise-engine/libsqlite3.so.0
precise-engine/_hashlib.cpython-34m-arm-linux-gnueabihf.so
precise-engine/libf77blas.so.3
precise-engine/libz.so.1
precise-engine/base_library.zip
precise-engine/libreadline.so.6
precise-engine/include/
precise-engine/include/python3.4m/
precise-engine/include/python3.4m/pyconfig.h
precise-engine/libbz2.so.1.0
precise-engine/libpython3.4m.so.1.0
precise-engine/readline.cpython-34m-arm-linux-gnueabihf.so
precise-engine/_codecs_jp.cpython-34m-arm-linux-gnueabihf.so
precise-engine/_codecs_cn.cpython-34m-arm-linux-gnueabihf.so
precise-engine/_codecs_tw.cpython-34m-arm-linux-gnueabihf.so
precise-engine/precise-engine
precise-engine/libcblas.so.3
precise-engine/libncursesw.so.5
precise-engine/_csv.cpython-34m-arm-linux-gnueabihf.so
precise-engine/_opcode.cpython-34m-arm-linux-gnueabihf.so
precise-engine/_curses.cpython-34m-arm-linux-gnueabihf.so
precise-engine/h5py/
precise-engine/h5py/_conv.cpython-34m.so
precise-engine/h5py/h5o.cpython-34m.so
precise-engine/h5py/h5fd.cpython-34m.so
precise-engine/h5py/_proxy.cpython-34m.so
precise-engine/h5py/utils.cpython-34m.so
precise-engine/h5py/h5.cpython-34m.so
precise-engine/h5py/h5f.cpython-34m.so
precise-engine/h5py/h5a.cpython-34m.so
precise-engine/h5py/h5g.cpython-34m.so
precise-engine/h5py/h5i.cpython-34m.so
precise-engine/h5py/h5ds.cpython-34m.so
precise-engine/h5py/h5l.cpython-34m.so
precise-engine/h5py/h5t.cpython-34m.so
precise-engine/h5py/defs.cpython-34m.so
precise-engine/h5py/h5d.cpython-34m.so
precise-engine/h5py/h5s.cpython-34m.so
precise-engine/h5py/_objects.cpython-34m.so
precise-engine/h5py/h5ac.cpython-34m.so
precise-engine/h5py/h5p.cpython-34m.so
precise-engine/h5py/h5r.cpython-34m.so
precise-engine/h5py/h5z.cpython-34m.so
precise-engine/h5py/_errors.cpython-34m.so
precise-engine/libtinfo.so.5
precise-engine/_codecs_hk.cpython-34m-arm-linux-gnueabihf.so
precise-engine/_multibytecodec.cpython-34m-arm-linux-gnueabihf.so
precise-engine/libexpat.so.1
precise-engine/_multiprocessing.cpython-34m-arm-linux-gnueabihf.so
precise-engine/_ctypes.cpython-34m-arm-linux-gnueabihf.so
precise-engine/_bz2.cpython-34m-arm-linux-gnueabihf.so
precise-engine/grpc/
precise-engine/grpc/_cython/
precise-engine/grpc/_cython/cygrpc.cpython-34m.so
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  472k  100  472k    0     0  1333k      0 --:--:-- --:--:-- --:--:-- 1333k
----------------------
Installation complete.
----------------------
Press enter to reboot your system now...


 SSH  192.168.178.36: session closed
Appuyez sur n'importe quelle touche pour vous reconnecter

**Comment by abstractfoundry** [comment]
Glad to hear you got it working @nsk. :+1:
