### ISSUE TITLE
502 Errror Downloading appimage from script

### ISSUE THREAD

**Issue by Findarato** [abstractfoundry/lumicube-daemon#7]
When I run the install script I am getting a 502 error downloading the appimage 

```
subprocess.CalledProcessError: Command 'curl -fL https://www.abstractfoundry.com/lumicube/download/Daemon-1.7-arm.AppImage > /home/pi/AbstractFoundry/Daemon/Software/Daemon-1.7-arm.AppImage' returned non-zero exit status 22.
```

Your website is not allowing downloading of the AppImage over Mullvad VPNs

**Comment by abstractfoundry** [comment]
Hi @Findarato I've published a GitHub release which hopefully you should be able to download instead:
https://github.com/abstractfoundry/lumicube-daemon/releases/tag/v1.7
You will have to modify the install script to set:
`binary_url = 'https://github.com/abstractfoundry/lumicube-daemon/releases/download/v1.7/Daemon-1.7-arm.AppImage'`
